# Generated by Django 3.1.2 on 2020-11-16 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('starttime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Rolelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilitator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilitator', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rolelist', to='agenda.meeting')),
                ('timer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timer', to=settings.AUTH_USER_MODEL)),
                ('toastmaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toastmaster', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
