# Generated by Django 3.1.2 on 2020-11-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_attendee'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolelist',
            name='absences',
            field=models.BooleanField(default=0),
        ),
    ]
