# Generated by Django 3.1.2 on 2020-12-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_auto_20201130_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='executive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_speech',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='meeting_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='speech_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='status',
            field=models.CharField(default='U', max_length=1),
        ),
    ]
