# Generated by Django 3.1.2 on 2020-12-14 09:07

import agenda.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0009_auto_20201214_0701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buglist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bug_type', models.CharField(max_length=100)),
                ('bug_location', models.CharField(max_length=100)),
                ('bug_description', models.CharField(max_length=2200)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=models.SET(agenda.models.get_deleted_user_instance), related_name='bugs_reported', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
