# Generated by Django 3.1.2 on 2020-12-14 10:33

import agenda.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0010_buglist'),
    ]

    operations = [
        migrations.AddField(
            model_name='buglist',
            name='contact_info',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='buglist',
            name='bug_description',
            field=models.CharField(blank=True, max_length=2200, null=True),
        ),
        migrations.AlterField(
            model_name='buglist',
            name='bug_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='buglist',
            name='bug_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='buglist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(agenda.models.get_deleted_user_instance), related_name='bugs_reported', to=settings.AUTH_USER_MODEL),
        ),
    ]
