# Generated by Django 3.1.2 on 2020-12-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0011_auto_20201214_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_speech',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
