# Generated by Django 3.1.2 on 2021-01-07 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0012_auto_20201215_0749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventlist_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_number', models.IntegerField(default=100)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('duration', models.IntegerField(default=7)),
                ('green_time', models.IntegerField(default=5)),
                ('yellow_time', models.IntegerField(default=6)),
                ('red_time', models.IntegerField(default=7)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventlist', to='agenda.meeting')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
