# Generated by Django 3.1.2 on 2021-01-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0014_auto_20210108_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlist',
            name='role',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
