# Generated by Django 3.1.2 on 2021-01-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0015_eventlist_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlist',
            name='role',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
