# Generated by Django 3.1.2 on 2021-01-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0017_rolelist_zoom'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='guestlist',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
    ]
